language: go
go:
- 1.12
script:
- echo "Test string"
- chmod 600 ./Certificate_rsa.pem
- ssh-keyscan -H 89.208.197.150 >> ~/.ssh/known_hosts
- scp -i ./Certificate_rsa.pem -r dist ubuntu@89.208.197.150:/home/ubuntu/backend
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_fae475b27048_key -iv $encrypted_fae475b27048_iv
  -in Certificate_rsa.cer.enc -out Certificate_rsa.cer -d
- openssl aes-256-cbc -K $encrypted_fae475b27048_key -iv $encrypted_fae475b27048_iv
  -in Certificate_rsa.cer.enc -out ../../Certificate_rsa.cer -d
