language: go
go:
- 1.12
script:
- go build ./cmd/apisrv/
- ls -la
- chmod 600 ./certificate_id_rsa.cer
- ssh-keyscan -H 89.208.197.150 >> ~/.ssh/known_hosts
- scp -i ./certificate_id_rsa.cer ubuntu@89.208.197.150 sudo systemctl stop apisrv.service
- scp -i ./certificate_id_rsa.cer -r ./apisrv ubuntu@89.208.197.150:/home/ubuntu/backend
- scp -i ./certificate_id_rsa.cer ubuntu@89.208.197.150 sudo systemctl start apisrv.service
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_fae475b27048_key -iv $encrypted_fae475b27048_iv
  -in certificate_id_rsa.cer.enc -out certificate_id_rsa.cer -d
