apisrv:
  host: 127.0.0.1
  port: 5000

authsrv:
  host: 127.0.0.1
  port: 5051

game:
  host: 127.0.0.1
  port: 8080
  static: static

db:
  host: localhost
  user: postgres
  password: 123456
  name: waogame
  sslmode: disable
  dump: ./dbase/dump.sql
  
secretkey: waosecret